{% set name = "libmemcached" %}
{% set series = "1.0" %}
{% set version = "1.0.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://launchpad.net/{{ name }}/{{ series }}/{{ version }}/+download/{{ name }}-{{ version }}.tar.gz
  sha256: e22c0bb032fde08f53de9ffbc5a128233041d9f33b5de022c0978a2149885f82
  patches:
    # thanks to http://stackoverflow.com/questions/27004144/how-can-i-install-libmemcached-for-mac-os-x-yosemite-10-10-in-order-to-install-t
    - osx.configure.patch  # [osx]
    - osx.memflush.patch  # [osx]
    # Taken from this bug report
    # ref: https://bugs.launchpad.net/libmemcached/+bug/1663985
    - libmemcached-build.patch  # [linux]

build:
  number: 1004
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # unix build chain
    - libtool  # [unix]
    - pkg-config  # [unix]
    # win build chain
    - autotools_clang_conda  # [win]
  host:
    - pthreads-win32    # [win]

test:
  commands:
    - test -f $PREFIX/lib/libmemcached.a  # [unux]
    - test -f $PREFIX/lib/libmemcached${SHLIB_EXT}  # [unix]

about:
  home: http://libmemcached.org
  license: BSD-3-Clause
  license_file: COPYING
  summary: libMemcached is an open source C/C++ client library and tools for the memcached server

extra:
  recipe-maintainers:
    - bollwyvl
